{
    "User ID": 188341441603305472,
    "Command": "m",
    "Args": [
        "<cogs.model.Model object at 0x000002A9CEE5CE10>",
        "<discord.ext.commands.context.Context object at 0x000002A9CED98668>",
        "enet",
        "0.5"
    ],
    "Kwargs": [],
    "Traceback": [
        "Traceback (most recent call last):\n",
        "  File \"D:\\Documents\\GitHub\\alwaysAI\\venv\\lib\\site-packages\\discord\\ext\\commands\\core.py\", line 83, in wrapped\n    ret = await coro(*args, **kwargs)\n",
        "  File \"D:\\Documents\\GitHub\\alwaysAI\\cogs\\model.py\", line 198, in model\n    image, results = categories[category](model, img_np)\n",
        "  File \"D:\\Documents\\GitHub\\alwaysAI\\cogs\\model.py\", line 141, in semantic_base\n    legend_image = Image.open(\"legend.png\")\n",
        "  File \"D:\\Documents\\GitHub\\alwaysAI\\venv\\lib\\site-packages\\PIL\\Image.py\", line 2878, in open\n    fp = builtins.open(filename, \"rb\")\n",
        "FileNotFoundError: [Errno 2] No such file or directory: 'legend.png'\n"
    ]
}